use miette::{miette, IntoDiagnostic, Result};
use std::path::Path;

const TEMPLATE: &str = r#"# Ark Architecture Configuration
# Generated by `ark init` — edit to match your solution.

layers = [
  { name = "Presentation",   patterns = ["*.Api", "*.Web", "*.Host"]                        },
  { name = "Application",    patterns = ["*.Application", "*.UseCases"]                     },
  { name = "Domain",         patterns = ["*.Domain", "*.Core"]                              },
  { name = "Infrastructure", patterns = ["*.Infrastructure", "*.Persistence", "*.Adapters"] },
]

# Any dependency not listed here is forbidden by default.
dependency_rules = [
  { from = "Presentation",   to = "Application",   allowed = true  },
  { from = "Application",    to = "Domain",         allowed = true  },
  { from = "Infrastructure", to = "Domain",         allowed = true  },
  { from = "Domain",         to = "Application",    allowed = false },
  { from = "Domain",         to = "Presentation",   allowed = false },
  { from = "Domain",         to = "Infrastructure", allowed = false },
]

package_policies = [
  # Domain should stay pure — no EF Core, no HTTP clients
  { layer = "Domain", forbidden = ["Microsoft.EntityFrameworkCore", "System.Net.Http"] },
]

ignore_patterns = ["*.Tests", "*.Specs", "*.IntegrationTests"]
"#;

pub fn run(root: &str) -> Result<()> {
    let dest = Path::new(root).join("architecture.toml");

    if dest.exists() {
        return Err(miette!(
            "architecture.toml already exists at {:?}. \
            Delete it first or edit it directly.",
            dest
        ));
    }

    std::fs::write(&dest, TEMPLATE).into_diagnostic()?;
    println!("Created {:?}", dest);
    println!("Edit it to match your solution, then run `ark check`.");
    Ok(())
}
