use std::path::Path;
use miette::{IntoDiagnostic, Result, miette};

const TEMPLATE: &str = r#"/// Ark Architecture Configuration
/// Generated by `ark init`

amends "pkl/ark.pkl"

layers {
  new {
    name = "Presentation"
    patterns { "*.Api"; "*.Web"; "*.Host" }
  }
  new {
    name = "Application"
    patterns { "*.Application"; "*.UseCases" }
  }
  new {
    name = "Domain"
    patterns { "*.Domain"; "*.Core" }
  }
  new {
    name = "Infrastructure"
    patterns { "*.Infrastructure"; "*.Persistence"; "*.Adapters" }
  }
}

dependencyRules {
  /// Presentation may call Application
  new { from = "Presentation"; to = "Application"; allowed = true }
  /// Application may call Domain
  new { from = "Application"; to = "Domain"; allowed = true }
  /// Infrastructure implements Domain interfaces — allowed
  new { from = "Infrastructure"; to = "Domain"; allowed = true }
  /// Domain must NOT depend on anything else
  new { from = "Domain"; to = "Application"; allowed = false }
  new { from = "Domain"; to = "Presentation"; allowed = false }
  new { from = "Domain"; to = "Infrastructure"; allowed = false }
}

packagePolicies {
  new {
    layer = "Domain"
    /// Domain should stay pure — no EF Core, no HTTP clients
    forbidden { "Microsoft.EntityFrameworkCore"; "System.Net.Http" }
  }
}
"#;

pub async fn run(root: &str) -> Result<()> {
    let dest = Path::new(root).join("architecture.pkl");

    if dest.exists() {
        return Err(miette!(
            "architecture.pkl already exists at {:?}. \
            Delete it first or edit it directly.",
            dest
        ));
    }

    std::fs::write(&dest, TEMPLATE).into_diagnostic()?;
    println!("Created {:?}", dest);
    println!("Edit it to match your solution, then run `ark check`.");
    Ok(())
}
